export const TEST_DISPATCH = "TEST_DISPATCH";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CATEGORY_DISPATCH = "CATEGORY_DISPATCH";
export const VIEW_CATEGORY_DISPATCH = "VIEW_CATEGORY_DISPATCH";
export const DELETE_CATEGORY_DISPATCH = "DELETE_CATEGORY_DISPATCH";

export const PRODUCT_DISPATCH = "PRODUCT_DISPATCH";

// for subcategories
export const SUBCATEGORY_DISPATCH = "SUBCATEGORY_DISPATCH";
export const VIEW_SUBCATEGORY_DISPATCH = "VIEW_SUBCATEGORY_DISPATCH";
export const ADD_SUBCATEGORY_DISPATCH = "ADD_SUBCATEGORY_DISPATCH";
export const UPDATE_SUBCATEGORY_DISPATCH = "UPDATE_SUBCATEGORY_DISPATCH";
export const DELETE_SUBCATEGORY_DISPATCH = "DELETE_SUBCATEGORY_DISPATCH";
